= ds18b20 Library for Arduino =
So nice ds18b20 : easy to get the real temperature with no count__remain or count_per_C and other like in ds18s20 .
only get 2 bytes : LSB=byte0 and MSB=byte1 ; instead of 9 bytes as in ds18s20 .


For more information about this library please visit us at
http://www.arduino.cc/en/Reference/My_ds18b20Library
github.com/badoudiop

== License ==

Copyright (c) 2014 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

upload and run and read the temperature on serial .
